### PR TITLE
Adding demos for Infineon AURIX TC375 using AURIX Development Studio

### PR DESCRIPTION
**Pull request by schaazzz**
Adding demos for Infineon AURIX TC375 using AURIX Development Studio

Description
-----------
FreeRTOS demos for the Infineon AURIX TC3xx FreeRTOS Kernel Port.

Test Steps
-----------
Setup, testing and debugging steps are described in detail in  `AURIX_TC375_ADS/README.md`

Related Issue
-----------
FreeRTOS/FreeRTOS-Kernel-Partner-Supported-Ports/pull/11

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by paulbartell** [comment]
Thanks very much for the contribution. Quite a few folks over the past few years have requested TriCore ports so i'm glad we have another set of demos to point them towards.

1. There are a tonne of files included in your PR. Would it be possible to include many of these via a git submodule rather than copying them into this repository? Keeping vendor-created code separate is preferred when possible to ease future maintenance.

2. Could you please add an SPDX License Identifier line to each file that is being added directly to the repository? Something like: ```SPDX-License-Identifier: BSL-1.0```

**Comment by schaazzz** [comment]
Thank you for taking the time to review this @paulbartell, I will modify the sources to include just the demo-specific files and update the README to include the steps to create an AURIX Development Studio project from scratch with these files

**Comment by n9wxu** [comment]
Can you please update the files to include the SPDX license identifiers?  We are now releasing SBOM's to assist users in identifying the components in a project.

**Review by amazonKamath — APPROVED** [review]

**Review by aggarg — APPROVED** [review]

**Comment by maxdd** [comment]
Can you please [verify ](https://community.infineon.com/t5/AURIX/How-to-run-freertos-on-TC3xx-core2/td-p/821998) the fact that this implementation is only working on Core0?
Changing configCPU_NR, although might set STM/SRC registers correctly, does not seem to trigger vPortSystemTickHandler()
Not sure if it is related to STM not counting because of a different core, the Ssw assumptions on Core0 as main starting/init core or even the interrupt vector table

Also can you add a note somewhere that GPSR0_SR0 is used for context switching?

**Comment by aggarg** [comment]
@schaazzz Would you please take a look at the above suggestion?

**Comment by maxdd** [comment]
As a reference, I'm using ADS 1.10.2 with tasking as compiler.
Would it be possibile to consider the use of (_mfcr(CPU_CORE_ID) to get the correct StmBase so that we don't need to edit the config file?

**Comment by maxdd** [comment]
Let me also add that on the stock example when i suspend the integrated ADS debugging session it takes 40s for the tasks to start behave normally again (e.g. led blinking). Is this happening to you as well? (i've tried with 1.9 and 1.10 ADS)

**Comment by marcocortecchia** [comment]
> Let me also add that on the stock example when i suspend the integrated ADS debugging session it takes 40s for the tasks to start behave normally again (e.g. led blinking). Is this happening to you as well? (i've tried with 1.9 and 1.10 ADS)

Is this issue solved ?

**Pull request merged**
