### PR TITLE
Update AVR_Mega0 and AVR_Dx demo projects 

### PR DESCRIPTION
**Pull request by mchpcristianpop**
Update AVR_Mega0 and AVR_Dx demo projects
-----------

Update AVR_Mega0 and AVR_Dx demo with CLI, Tickless and Percepio Tracealyser example projects
Update projects paths to new structure 

Test Steps
-----------

Related Issue
-----------

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by aggarg — DISMISSED** [review]

**Comment by aggarg** [comment]
Can you not use the common files from the [FreeRTOS/FreeRTOS](https://github.com/FreeRTOS/FreeRTOS) repo? This repo is submoduled in the [FreeRTOS/FreeRTOS](https://github.com/FreeRTOS/FreeRTOS) repo.

**Comment by mchpcristianpop** [comment]
That's means to include files direct into projects? In [this page](https://github.com/FreeRTOS/FreeRTOS/tree/main/FreeRTOS/Demo/ThirdParty/Template) is mentioned that files from  [FreeRTOS/Demo/Common/Minimal ](https://github.com/FreeRTOS/FreeRTOS/tree/main/FreeRTOS/Demo/Common/Minimal) could be used.

**Comment by aggarg** [comment]
Apologies for unclear comment. I meant about files in ` AVR_ATMega4809_Atmel_Studio/RTOSDemo/Common` directory.

**Comment by aggarg** [comment]
> 
> 
> That's means to include files direct into projects? In [this page](https://github.com/FreeRTOS/FreeRTOS/tree/main/FreeRTOS/Demo/ThirdParty/Template) is mentioned that files from [FreeRTOS/Demo/Common/Minimal ](https://github.com/FreeRTOS/FreeRTOS/tree/main/FreeRTOS/Demo/Common/Minimal) could be used.

Yes - all I wanted to point that you do not need to copy these files and you can directly reference those files.

**Comment by mchpcristianpop** [comment]
> > That's means to include files direct into projects? In [this page](https://github.com/FreeRTOS/FreeRTOS/tree/main/FreeRTOS/Demo/ThirdParty/Template) is mentioned that files from [FreeRTOS/Demo/Common/Minimal ](https://github.com/FreeRTOS/FreeRTOS/tree/main/FreeRTOS/Demo/Common/Minimal) could be used.
> 
> Yes - all I wanted to point that you do not need to copy these files and you can directly reference those files.

Thank you for feedback! I'll update this PR

**Review by aggarg — APPROVED** [review]

**Review by cobusve — APPROVED** [review]

**Pull request merged**
